
export const OPEN_SNACKBAR = "OPEN_SNACKBAR"
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"

export const SIGNIN = "SIGNIN"
export const SIGNOUT = "SIGNOUT"

export const SOCKET_CONNECTION_REQUEST = "SOCKET_CONNECTION_REQUEST"
export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS"
export const SOCKET_CONNECTION_ERROR = "SOCKET_CONNECTION_ERROR"
export const SOCKET_CONNECTION_DISCONNECTED = "SOCKET_CONNECTION_DISCONNECTED"

export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST"
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS"
export const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR"

export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST"
export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS"
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR"
export const RESET_SEARCH = "RESET_SEARCH"

export const ADD_EMPTY_MESSAGES_ARRAY = "ADD_EMPTY_MESSAGES_ARRAY"
export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR"
export const ADD_ONE_MESSAGE = "ADD_ONE_MESSAGE"
export const UPDATE_ONE_MESSAGE = "UPDATE_ONE_MESSAGE"
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT"

