
export const OPEN_SNACKBAR = "OPEN_SNACKBAR"
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"

export const SIGNIN = "SIGNIN"
export const SIGNOUT = "SIGNOUT"

// export const SOCKET_CONNECTION_REQUEST = "SOCKET_CONNECTION_REQUEST"
// export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS"
// export const SOCKET_CONNECTION_ERROR = "SOCKET_CONNECTION_ERROR"

export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST"
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS"
export const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR"

export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST"
export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS"
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR"
export const RESET_SEARCH = "RESET_SEARCH"

