export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_CONNECTING = "SOCKET_CONNECTING";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_ERROR = "SOCKET_ERROR";